name: CI/CD completo Examen HLM

env:
  IMAGE_NAME: api-lasanta:latest
  # FILES: compose.yml

# GitHub Secrets
# USER_DH
# TOKEN_DH
# IP_EC2
# USER_EC2
# CLAVE_EC2

on:
  push:
    branches: [ main ]  
    # se comenta para no interferir en protección de ramas
    # paths:
    #   - '**.py'

jobs:

  scan:
   name: gitleaks
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0
     - uses: gitleaks/gitleaks-action@v2
     - name: test
       run: |
            gitleaks dir >> $GITHUB_STEP_SUMMARY
       # env:
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       #   GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not personal accounts.

  lint:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=79 --statistics

  build_and_push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER_DH }}
          password: ${{ secrets.TOKEN_DH }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.USER_DH }}/${{ env.IMAGE_NAME }}

  deploy:
    name: deploy en AWS
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_EC2 }}
          username: ${{ secrets.USER_EC2 }}
          key: ${{ secrets.CLAVE_EC2 }}
          port: 22 # ${{ secrets.PORT }}
          script: |
            sleep 30
            docker rm -f web1
            docker rmi ${{ secrets.USER_DH }}/${{ env.IMAGE_NAME }}
            docker run -d -p 80:8000 --name web1 ${{secrets.USER_DH}}/${{env.IMAGE_NAME}}

  connection_test:
    name: test de conexión
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Connection test using curl
        run: |
          curl ${{ secrets.IP_EC2 }}/version
